# Generated by Django 4.1 on 2022-08-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dao_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
